function hasPrimaryKey(table) {
  return table.constraints.some((c) => c.type === 'PRIMARY_KEY');
}

function isColumnIndexed(schema, tableName, columnName) {
  const table = schema.tables.get(tableName);
  if (!table) return false;

  const pkConstraint = table.constraints.find((c) => c.type === 'PRIMARY_KEY' && c.columns.includes(columnName));
  if (pkConstraint) return true;

  return schema.indexes.some((idx) => idx.table === tableName && idx.columns.includes(columnName));
}

function runChecks(schema) {
  const findings = [];

  for (const table of schema.tables.values()) {
    if (!hasPrimaryKey(table)) {
      findings.push({
        id: 'P0_NO_PRIMARY_KEY',
        title: 'Table has no primary key',
        severity: 'P0',
        description: 'Tables without a primary key risk duplicates and unsafe updates.',
        evidence: [`table ${table.name}`],
        suggestedFix: `ALTER TABLE ${table.name} ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY;`,
      });
    }

    const moneyFloatCols = table.columns.filter(
      (c) => /(amount|price|cost|total|balance)/i.test(c.name) && /\b(real|double precision|float\d*)\b/i.test(c.type),
    );
    if (moneyFloatCols.length > 0) {
      findings.push({
        id: 'P0_FLOAT_FOR_MONEY',
        title: 'Float type used for money-like column',
        severity: 'P0',
        description: 'Floating-point types can introduce rounding errors in financial calculations.',
        evidence: moneyFloatCols.map((c) => `${table.name}.${c.name} ${c.type}`),
        suggestedFix: `ALTER TABLE ${table.name} ALTER COLUMN <column> TYPE numeric(18,2);`,
      });
    }

    const textTimestampCols = table.columns.filter(
      (c) => /(time|date|created|updated)/i.test(c.name) && /^(text|varchar(\([^)]*\))?)$/i.test(c.type),
    );
    if (textTimestampCols.length > 0) {
      findings.push({
        id: 'P0_TEXT_FOR_TIMESTAMP',
        title: 'Timestamp-like column stored as text/varchar',
        severity: 'P0',
        description: 'Text timestamps can break ordering, validation, and query performance.',
        evidence: textTimestampCols.map((c) => `${table.name}.${c.name} ${c.type}`),
        suggestedFix: `ALTER TABLE ${table.name} ALTER COLUMN <column> TYPE timestamptz USING <column>::timestamptz;`,
      });
    }

    const nullableIdCols = table.columns.filter((c) => /_id$/i.test(c.name) && !c.notNull);
    if (nullableIdCols.length > 0) {
      findings.push({
        id: 'P1_NULLABLE_ID_COLUMN',
        title: 'Nullable *_id column',
        severity: 'P1',
        description: 'Nullable identifier/foreign key columns can lead to orphaned and inconsistent records.',
        evidence: nullableIdCols.map((c) => `${table.name}.${c.name}`),
        suggestedFix: `ALTER TABLE ${table.name} ALTER COLUMN <column> SET NOT NULL;`,
      });
    }

    const missingFkIndexes = table.columns.filter((c) => /_id$/i.test(c.name) && !isColumnIndexed(schema, table.name, c.name));
    if (missingFkIndexes.length > 0) {
      findings.push({
        id: 'P1_MISSING_INDEX_ON_ID_COLUMN',
        title: 'Missing index on *_id column',
        severity: 'P1',
        description: 'Foreign-key-style columns without indexes can cause slow joins and lock-heavy parent deletes.',
        evidence: missingFkIndexes.map((c) => `${table.name}.${c.name}`),
        suggestedFix: `CREATE INDEX CONCURRENTLY idx_${table.name}_<column> ON ${table.name} (<column>);`,
      });
    }

    const jsonCols = table.columns.filter((c) => /\b(json|jsonb)\b/i.test(c.type));
    if (jsonCols.length > 0) {
      findings.push({
        id: 'P2_JSON_USAGE',
        title: 'JSON/JSONB column present',
        severity: 'P2',
        description: 'JSON fields are flexible but can become expensive to query and index if overused.',
        evidence: jsonCols.map((c) => `${table.name}.${c.name} ${c.type}`),
        suggestedFix: 'For hot JSON paths, extract typed columns and/or add targeted GIN indexes.',
      });
    }

    const serialCols = table.columns.filter((c) => /\b(smallserial|serial|bigserial)\b/i.test(c.type));
    if (serialCols.length > 0) {
      findings.push({
        id: 'P2_SERIAL_USAGE',
        title: 'SERIAL family used instead of IDENTITY',
        severity: 'P2',
        description: 'IDENTITY columns are the modern Postgres standard and reduce sequence ownership pitfalls.',
        evidence: serialCols.map((c) => `${table.name}.${c.name} ${c.type}`),
        suggestedFix: 'Prefer `GENERATED BY DEFAULT AS IDENTITY` for new columns/tables.',
      });
    }
  }

  if (schema.enums.length > 0) {
    findings.push({
      id: 'P2_ENUM_USAGE',
      title: 'ENUM type usage detected',
      severity: 'P2',
      description: 'ENUM changes can add migration friction for frequently changing business states.',
      evidence: schema.enums.map((e) => `${e.name} values: ${e.values.join(', ')}`),
      suggestedFix: 'Consider lookup tables + foreign keys (or controlled smallint mapping) for rapidly changing states.',
    });
  }

  return findings;
}

module.exports = { runChecks };
